name: Verificacion Develop
on:
  push:
    branches: 
      - develop
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ develop  ]
jobs:
  job1:
    name: Pruebas backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      working-directory: flaskr
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: pytest -v
  job2:
    name: Pruebas Front-End
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Instalar dependencies
      run: npm install
      working-directory: front-end/tutorial-canciones
    - name: Build
      run: npm run build
      working-directory: front-end/tutorial-canciones   
    - name: Test
      run: npm test
      working-directory: front-end/tutorial-canciones   


